// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

namespace SmartSchool.WebApi.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20211129162743_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 881, DateTimeKind.Local).AddTicks(2551),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 882, DateTimeKind.Local).AddTicks(9888),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 882, DateTimeKind.Local).AddTicks(9970),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 882, DateTimeKind.Local).AddTicks(9991),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 883, DateTimeKind.Local).AddTicks(4),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 883, DateTimeKind.Local).AddTicks(59),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 883, DateTimeKind.Local).AddTicks(80),
                            DataNasc = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 883, DateTimeKind.Local).AddTicks(7798)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1479)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1500)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1500)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1507)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1527)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1527)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1534)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1534)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1548)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1548)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1554)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1554)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1561)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1561)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1568)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1575)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1582)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1589)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1589)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1596)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1596)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 884, DateTimeKind.Local).AddTicks(1602)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargaHoraria")
                        .HasColumnType("TEXT");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreRequisitoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PreRequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 824, DateTimeKind.Local).AddTicks(6535),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 826, DateTimeKind.Local).AddTicks(2600),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 826, DateTimeKind.Local).AddTicks(2641),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 826, DateTimeKind.Local).AddTicks(2648),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataMatricula = new DateTime(2021, 11, 29, 13, 27, 41, 826, DateTimeKind.Local).AddTicks(2648),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "PreRequisito")
                        .WithMany()
                        .HasForeignKey("PreRequisitoId");

                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
